### ISSUE TITLE
Add a vehicle enquiry service

### ISSUE THREAD

**Issue by lukeeey** [StatesOfJersey/SoJ-CSS#3]
like https://vehicleenquiry.service.gov.uk

I know its nothing to do with this repo but im too lazy to email

**Comment by marcusferbrache** [comment]
What info would you want the service to return?

**Comment by lukeeey** [comment]
Its not important or anything but i feel it would be nice to create some software like https://github.com/kslat3r/anpr-dashcam . Just a thought, and if a service like that was not created then it would be nice to see some more open source stuff on this github organization like the UK govenment has done.
